good_add_new:
  file_path: "/Users/yuanyuanhe/Desktop/货/拍品导入/11-1.csv"
  begin_time: "2022-11-11 10:00:00"
  end_time: "2022-11-14 20:00:00"
  topic_id: "[82]"

goods_bid:
  file_path:  "/Users/yuanyuanhe/Desktop/货/拍品出价详情/11-1-202211417.csv"
  good_id: 3409
  num: 24



