new_unions:
  file_path: "/Users/yuanyuanhe/Desktop/货/推广活动导入/5-3.csv"
  unions_info:
    "begin_time": "2023-05-19 10:00:00"
    "end_time": "2023-06-06 20:00:00"
    "topic_id": [105]

mini_url:
  mini_url1: pagesB/pages/transation/index
  mini_url2: pagesB/pages/transaction/history?note_number=869a